application:
  
  # 输入配置
  input:
    - name: 'AWAvenue-Ads-Rule'               #可选参数: 规则名称，如无将使用 path 作为名称
      path: 'https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt' #必要参数: 规则 url (http/https) 或 本地文件位置 (绝对/相对路径)
      type: easylist                       #可选参数: 规则类型：easylist (默认)、dnsmasq、clash、smartdns、hosts

    - name: 'xinggsf mv'
      path: 'https://raw.githubusercontent.com/xinggsf/Adblock-Plus-Rule/master/mv.txt'
      type: easylist

    - name: 'jiekouAD'
      path: 'https://raw.githubusercontent.com/damengzhu/banad/main/jiekouAD.txt'
      type: easylist  

    - name: 'AD-J'
      path: 'https://raw.githubusercontent.com/jk278/Ad-J/main/Ad-J.txt'
      type: easylist

    - name: 'GOODBYEADS-白名单'
      path: 'https://raw.githubusercontent.com/8680/GOODBYEADS/master/data/rules/allow.txt'
      type: easylist

    - name: 'halflife-list'
      path: 'https://cdn.jsdelivr.net/gh/sbwml/halflife-list@master/ad.txt'
      type: easylist  
      
  # 输出配置
  output:
    #文件头配置，将自动作为注释添加至每个规则文件开始
    #可使用占位符 ${name}、${type}、${desc} 以及 ${date} (当前日期)、${total} (规则总数)
    file_header: |
      ChengZhouCR AdBlock ${type}
      Last Modified: ${date}
      Total Size: ${total}
      Desc: ${desc}
      Homepage: https://github.com/chengzhouCR/ad-filters-subscriber/
      
    files:
      - name: smartdns.conf    #必要参数: 文件名
        type: smartdns         #必要参数: 文件类型: easylist、dnsmasq、clash、smartdns、hosts
        file_header:           #可选参数: 文件头配置，将自动作为注释添加至每个规则文件开始 (此处优先于 output.file_header)
        desc: 'ChengZhouCR自用的SmartDNS去广告规则，规则较为精简，每日自动更新。规则源：AWAvenue Ads Rule、xinggsf mv、jiekouAD、AD-J、GOODBYEADS-白名单、halflife-list。'  #可选参数: 文件描述，可在file_header中通过 ${} 中使用
        filter:
          - basic              #基本规则，不包含任何控制、匹配符号, 可以转换为 hosts
          - wildcard           #通配规则，仅使用通配符
          - unknown            #其他规则，如使用了正则、高级修饰符号的规则，这些规则目前无法转换为其他格式
                               #可选参数: 限定此文件使用的规则源，如果不指定则使用 input 中的所有规则源   
