application:
  config:
    domain-detect:
      enable: true
      timeout: 3000
      concurrency: 128
      provider:
        - 1.1.1.1
        - 8.8.8.8    
  
  # 输入配置
  input:
    - name: 'AWAvenue-Ads-Rules'               
      path: 'https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt' 

    - name: 'jiekouAD'
      path: 'https://raw.githubusercontent.com/damengzhu/banad/main/jiekouAD.txt'
      type: easylist

    - name: 'halflife-list'
      path: 'https://cdn.jsdelivr.net/gh/sbwml/halflife-list@master/ad.txt'
      type: easylist

    - name: '不是DD啊'
      path: 'https://raw.githubusercontent.com/afwfv/DD-AD/main/rule/DD-AD.txt'
      type: easylist

    - name: '海哥规则'
      path: 'https://raw.githubusercontent.com/2771936993/HG/main/hg1.txt'
      type: easylist

    - name: '晴雅广告拦截规则重置版'
      path: 'https://raw.githubusercontent.com/790953214/qy-Ads-Rule/main/black.txt'
      type: easylist

    - name: 'lingeringsound规则'
      path: 'https://raw.githubusercontent.com/lingeringsound/adblock_auto/main/base/%E5%85%B6%E4%BB%96.prop'
      type: easylist

    - name: '茯苓规则'
      path: 'https://raw.githubusercontent.com/Kuroba-Sayuki/FuLing-AdRules/Master/FuLingRules/FuLingBlockList.txt'
      type: easylist

    - name: '217heidai'
      path: 'https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockdnslite.txt'
      type: easylist  
      
  # 输出配置
  output:
    #文件头配置，将自动作为注释添加至每个规则文件开始
    #可使用占位符 ${name}、${type}、${desc} 以及 ${date} (当前日期)、${total} (规则总数)
    file_header: |
      ChengZhouCR AdBlock ${type}
      Last Modified: ${date}
      Total Size: ${total}
      Homepage: https://github.com/chengzhouCR/AdBlock-Rules
      Description: 自用的路由器去广告规则，规则较为精简，每日自动更新。上游规则源：AWAvenue Ads Rule、jiekouAD、halflife-list、不是DD啊、海哥规则、晴雅规则、lingeringsound规则、茯苓规则、217heidai规则精简版。
      
    files:
      - name: smartdns.conf    
        type: smartdns         
                               
      - name: dns.txt
        type: easylist                 
        filter:
          - basic             
          - wildcard
      
      - name: dnsmasq.conf
        type: dnsmasq                

      - name: hosts
        type: hosts        
        
      - name: clash.yaml
        type: clash        
