application:
  config:
    domain-detect:
      enable: true
      timeout: 3000
      concurrency: 128
      provider:
        - 1.1.1.1
        - 8.8.8.8

    tracking:
      enable: true
      path: logs/tracking.list    
  
  # 输入配置
  input:
    - name: 'AWAvenue-Ads-Rules'               
      path: 'https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/AWAvenue-Ads-Rule.txt'   
  
    - name: 'DD-AD规则'
      path: 'https://raw.githubusercontent.com/afwfv/DD-AD/refs/heads/release/DD-AD.txt'
      type: easylist

    - name: '茯苓拦截列表'
      path: 'https://raw.githubusercontent.com/Kuroba-Sayuki/FuLing-AdRules/Master/FuLingRules/FuLingBlockList.txt'
      type: easylist 

    - name: '茯苓允许列表'
      path: 'https://raw.githubusercontent.com/Kuroba-Sayuki/FuLing-AdRules/Master/FuLingRules/FuLingAllowList.txt'
      type: easylist

    - name: 'who520-黑名单'
      path: 'https://raw.githubusercontent.com/qq5460168/dangchu/main/black.txt'
      type: easylist

    - name: 'who520-白名单'
      path: 'https://raw.githubusercontent.com/qq5460168/dangchu/main/white.txt'
      type: easylist  
      
  # 输出配置
  output:
    #文件头配置，将自动作为注释添加至每个规则文件开始
    #可使用占位符 ${name}、${type}、${desc} 以及 ${date} (当前日期)、${total} (规则总数)
    file_header: |
      AdBlock-Router ${type}
      Last Modified: ${date}
      Total Size: ${total}
      Homepage: https://github.com/chengzhouCR/AdBlock-Rules
      Description: 自用的路由器去广告规则，每日自动更新，上游规则：AWAvenue Ads Rule、DD-AD规则、茯苓广告规则、who520规则。
      
    files:
      - name: smartdns.conf    
        type: smartdns         
                               
      - name: dns.txt
        type: easylist                 
        filter:
          - basic             
          - wildcard
      
      - name: dnsmasq.conf
        type: dnsmasq                

      - name: hosts
        type: hosts        
        
      - name: clash.yaml
        type: clash        
